/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface AccAutocomplete {
    'closeOptions': () => void;
    'isAsync': boolean;
    'items': string;
    'label': string;
    'labelBy': string;
    'setLabel': (newLabel: string) => void;
  }
  interface AccAutocompleteAttributes extends StencilHTMLAttributes {
    'isAsync'?: boolean;
    'items'?: string;
    'label'?: string;
    'labelBy'?: string;
    'onValueSelected'?: (event: CustomEvent) => void;
  }

  interface AccVersion {}
  interface AccVersionAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'AccAutocomplete': Components.AccAutocomplete;
    'AccVersion': Components.AccVersion;
  }

  interface StencilIntrinsicElements {
    'acc-autocomplete': Components.AccAutocompleteAttributes;
    'acc-version': Components.AccVersionAttributes;
  }


  interface HTMLAccAutocompleteElement extends Components.AccAutocomplete, HTMLStencilElement {}
  var HTMLAccAutocompleteElement: {
    prototype: HTMLAccAutocompleteElement;
    new (): HTMLAccAutocompleteElement;
  };

  interface HTMLAccVersionElement extends Components.AccVersion, HTMLStencilElement {}
  var HTMLAccVersionElement: {
    prototype: HTMLAccVersionElement;
    new (): HTMLAccVersionElement;
  };

  interface HTMLElementTagNameMap {
    'acc-autocomplete': HTMLAccAutocompleteElement
    'acc-version': HTMLAccVersionElement
  }

  interface ElementTagNameMap {
    'acc-autocomplete': HTMLAccAutocompleteElement;
    'acc-version': HTMLAccVersionElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
